#pragma once
#ifndef FELPS_ERR_H_
#define FELPS_ERR_H_

typedef enum {
  FELPS_ERR_NONE = 0,
  FELPS_ERR_UNKNOWN,
  FELPS_ERR_MULTIPLE,
  FELPS_ERR_NOT_IMPLEMENTED,
  FELPS_ERR_BUSY,
  FELPS_ERR_OUT_OF_MEM,
  FELPS_ERR_BAD_PARAM,
  FELPS_ERR_BAD_CONFIG,
  FELPS_ERR_BAD_PART,
  FELPS_ERR_NOT_FOUND,
  FELPS_ERR_DROPPED_MSG,
  FELPS_ERR_BAD_BUF,
} felps_err_e;

#endif // FELPS_ERR_H_